#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# webserver 
cookbook 'apt'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'php'
cookbook 'php-fpm'
cookbook 'sqlite'
cookbook 'nginx'
cookbook 'memcached'
cookbook 'imagemagick'
cookbook 'hosts'

# zsh
cookbook 'chef-solo-search'
cookbook 'zsh'
cookbook 'oh-my-zsh'

#php-dev
cookbook 'composer'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
